# recover和defer

这是腾讯面试一道题，记住这个陷阱

```go
func main() {
    defer func() {
        if r := recover(); r != nil {
           fmt.Println("recover success")
        }
     }()

     go func() {
        panic("panic")
     }()
}
```

这个函数不会recover到panic的，可以看看这篇文章 https://studygolang.com/articles/24044?fr=sidebar。

defer recover这种机制只是针对当前函数和以及直接调用的函数可能产生的panic，它无法处理其调用产生的其它协程的panic，这一点和try catch机制不一样。理论上讲，所有使用协程的地方都必须做defer recover处理。

必须要和有异常的栈帧只隔一个栈帧，`recover`函数才能正常捕获异常。换言之，`recover`函数捕获的是祖父一级调用函数栈帧的异常（刚好可以跨越一层`defer`函数）！



**参考：**  [微信文章defer](https://mp.weixin.qq.com/s/txj7jQNki_8zIArb9kSHeg)